name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Set environment variables
      run: |
        echo "ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" >> $GITHUB_ENV
        echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> $GITHUB_ENV
        echo "ADMIN_PHONE_NUMBER=${{ secrets.ADMIN_PHONE_NUMBER }}" >> $GITHUB_ENV
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
      shell: bash
    - name: Run Playwright tests
      run: npx playwright test
    - name: Deploy Report to GitHub Pages
      if: ${{ !cancelled() }}
      run: |
        # Set up git
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        # Check out the ghPages branch or create it if it doesn't exist
        git fetch origin ghPages || git checkout --orphan ghPages
        git worktree add ghPages ghPages
        cd ghPages
        
        # Clear the ghPages branch content
        rm -rf ./*
        
        # Copy the Playwright report to the ghPages branch
        cp -R ../playwright-report/* .
        
        # Commit and push the report to the ghPages branch
        git add .
        git commit -m "Update Playwright report" || echo "No changes to commit"
        git push origin ghPages
